### ISSUE TITLE
Not assigning the enumeration when tweaking the primary and foreign key

### ISSUE THREAD

**Issue by DamirSvrtan** [infinum/enumerations#32]
```ruby
class FormStep < Enumerations::Base
  value :hello, id: 1
  value :bye,   id: 2
end
```

```ruby
class FormFillingSession < ApplicationRecord
  enumeration :step, primary_key: :id, foreign_key: :step_id, class_name: FormStep
end
```

Let's add a test for this and see why it does not work.

**Comment by PetarCurkovic** [comment]
We cannot use `primary_key` config like this. 

Primary key config refers a class that inherited `Enumerations::Base` class and it must be defined inside that class. That's because the enumeration class must exist before you call `enumeration` method inside model.

In PR #37, I've introduced `primary_key=` class method which allows you to set primary_key for each enumerations class.
