### ISSUE TITLE
Uniqueness validation on enumerations field

### ISSUE THREAD

**Issue by nikajukic** [infinum/enumerations#42]
You can't add uniqueness validation (normal or scoped to another attribute) on enumeration attribute.

```
class Order
  enumeration :status

  validates :status, uniqueness: true #this doesn't work
end

class Status < Enumerations::Base
  value :pending, name: 'Pending'
  value :finished, name: 'Finished'
end
```
This raises:
```
TypeError: can't cast Status
from /Users/infinum/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/quoting.rb:45:in `rescue in type_cast'
```

Fix:
```
class Status < Enumerations::Base
  value :pending, name: 'Pending'
  value :finished, name: 'Finished'

  def quoted_id
    id
  end

  def id
    symbol.to_s
  end
end
```

**Comment by uncoverd** [comment]
Hey @PetarCurkovic , I have an update for you 😅 

The Rails 5.2 attribute API changes break uniqueness validations in some cases even with the hack that was posted above. The result is the same error
```
TypeError:
       can't cast AddressType
```
This is an issue for us as we can't make the push to Rails 5.2.3.

 The crux of the issue is https://github.com/rails/rails/issues/29639.

> You should not implement quoted_id. You need to change your type to not rely on calling id anymore.
> You are missing an implementation of `serialize` in your type. You need to convert from `MyType` to something that the database knows how to deal with (likely you just need to call `.id`). The deprecation warning is correctly telling you that you cannot rely on this happening automatically anymore.


Here is the minimal reproduction script I managed to write. Change the Rails version between 5.1.5 and to 5.2 to see it fail.
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "sqlite3", '~> 1.3.13'
  gem "activerecord", '5.2'
  gem 'enumerations'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :personal_multitracks do |t|
    t.integer :user_id
  end

  add_column :personal_multitracks, :status, :string, null: false, default: :creating

  create_table :users, force: true do |t|
    t.string :name
  end
end

class BaseEnumerations < Enumerations::Base
  def quoted_id
    id
  end

  def id
    symbol.to_s
  end

  def key
    symbol
  end
end

class Status < BaseEnumerations
  value :creating,   name: 'Creating'
  value :processing, name: 'Processing'
  value :finished,   name: 'Finished'
end


class PersonalMultitrack < ActiveRecord::Base
  enumeration :status, class_name: 'Status'

  belongs_to :user

  validates :status, presence: true
  validates :status, uniqueness: true
end


class User < ActiveRecord::Base
  has_many :personal_multitracks, dependent: :destroy
end


class BugTest < Minitest::Test
  def test_type_cast
    user = User.create

    PersonalMultitrack.create(status: :creating, user: user)

    assert_equal 1, PersonalMultitrack.count
  end
end

```
The `quoted_id` hack on BaseEnumerations kept it working until 5.2. Now that method isn't being called anymore and we need to move to attributes.

Our temporary fix was to add an ActiveRecord Type
```
class Enumeration < ActiveRecord::Type::String
	  def serialize(value)
	    value.to_s
	  end
	end
```
and a corresponding attribute declaration
```
attribute :status, :enumeration
```

I imagine we are not the only ones using quoted_id 😄 Do you think it would make sense to include a README section on 5.2 attributes or better yet conform to the new Rails APIs and make this configuration a part of the gem?

**Comment by uncoverd** [comment]
Ping 😃
